### ISSUE TITLE
Invalidaded message gone but add-to-cart problem persists

### ISSUE THREAD

**Issue by onepack** [sprankhub/Spranks_RefreshBlockHtmlCache#1]
I have a problem that when the cache invalidates a customer cannot add products to the cart from the new products after a product save in the backend (->cache invalidated).
Your module seems to get rid of the cache invalidated message after a product save but the problem that a customer cannot add to cart after a product save persists.
Magento 1.9.1.0

**Comment by sprankhub** [comment]
Just tried and could not reproduce with a fresh 1.9.1 install and the rwd/default theme.

**Comment by onepack** [comment]
Ok, no worries. I fixed my issue by disabling the cache on the specific blocks via cms.xml http://stackoverflow.com/questions/20563958/magento-add-to-cart-issue-on-caching-new-products
