### ISSUE TITLE
Clear Invalid Cache per Cron

### ISSUE THREAD

**Issue by mklooss** [sprankhub/Spranks_RefreshBlockHtmlCache#2]
Hey,

i also build the extension from the gist ( https://gist.github.com/tonigrigoriu/1074482 ) entry.
and i also added an crontab to find out wich cache is invalid an clean this cache automaticly:

https://github.com/mklooss/Loewenstark_InvalidCache/blob/master/app/code/community/Loewenstark/InvalidCache/Model/Observer.php#L23

**Comment by sprankhub** [comment]
Looks nice. Thanks for the information! You just may want to enhance the README a bit :)
